export const healthStats = [
  { label: "Total", value: "9", icon: "hub" },
  { label: "Healthy", value: "7", icon: "check_circle", tone: "success" },
  { label: "Degraded", value: "1", icon: "warning", tone: "warning" },
  { label: "Down", value: "0", icon: "error", tone: "danger" },
  { label: "Blocked", value: "0", icon: "block" },
  { label: "Unconfigured", value: "0", icon: "settings_suggest" },
];

export const headroomProxy = {
  url: "http://localhost:8787",
  state: "Healthy",
  tone: "success",
};

export const connections = [
  {
    id: "minimax-heitor",
    connection: "MiniMax Heitor",
    provider: "minimax",
    state: "Healthy",
    tone: "success",
    status: "200",
    latency: "636ms",
    error: "—",
  },
  {
    id: "claude-code",
    connection: "Claude Code",
    provider: "anthropic",
    state: "Healthy",
    tone: "success",
    status: "200",
    latency: "412ms",
    error: "—",
  },
  {
    id: "openai-primary",
    connection: "OpenAI Primary",
    provider: "openai",
    state: "Healthy",
    tone: "success",
    status: "200",
    latency: "284ms",
    error: "—",
  },
  {
    id: "codex-workspace",
    connection: "Codex Workspace",
    provider: "codex",
    state: "Healthy",
    tone: "success",
    status: "200",
    latency: "338ms",
    error: "—",
  },
  {
    id: "gemini-production",
    connection: "Gemini Production",
    provider: "google",
    logoProvider: "gemini",
    state: "Healthy",
    tone: "success",
    status: "200",
    latency: "507ms",
    error: "—",
  },
  {
    id: "xai-reasoning",
    connection: "xAI Reasoning",
    provider: "xai",
    state: "Healthy",
    tone: "success",
    status: "200",
    latency: "689ms",
    error: "—",
  },
  {
    id: "mistral-backup",
    connection: "Mistral Backup",
    provider: "mistral",
    state: "Healthy",
    tone: "success",
    status: "200",
    latency: "451ms",
    error: "—",
  },
  {
    id: "ollama-local",
    connection: "Ollama Local",
    provider: "ollama",
    state: "Degraded",
    tone: "warning",
    status: "404",
    latency: "21ms",
    error: "HTTP 404",
  },
  {
    id: "bedrock-lab",
    connection: "Bedrock Lab",
    provider: "aws-bedrock",
    state: "Unknown",
    tone: "neutral",
    status: "—",
    latency: "—",
    error: "Awaiting first check",
  },
];
