export default {
  id: "auggie",
  priority: 45,
  hasFree: true,
  alias: "aug",
  uiAlias: "aug",
  display: {
    name: "Augment Auggie CLI",
    icon: "terminal",
    color: "#0F766E",
    textIcon: "AG",
    website: "https://augmentcode.com",
    notice: {
      text: "Runs the local auggie CLI. Install Auggie, run auggie login outside DurinDoor, then use this no-auth provider.",
    },
  },
  category: "free",
  noAuth: true,
  autoComboNoAuth: true,
  transport: {
    baseUrl: "auggie://cli/stdio",
    format: "openai",
    noAuth: true,
  },
  models: [
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6", contextLength: 200000 },
    { id: "claude-sonnet-4.6-thinking", name: "Claude Sonnet 4.6 Thinking", contextLength: 200000 },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6", contextLength: 200000 },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", contextLength: 200000 },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro", contextLength: 1000000 },
    { id: "gemini-3.0-flash", name: "Gemini 3 Flash", contextLength: 1000000 },
    { id: "gpt-5.5-high", name: "GPT-5.5 High", contextLength: 200000 },
    { id: "gpt-5.5-medium", name: "GPT-5.5 Medium", contextLength: 200000 },
    { id: "gpt-5.4-high", name: "GPT-5.4 High", contextLength: 200000 },
    { id: "gpt-5.4-medium", name: "GPT-5.4 Medium", contextLength: 200000 },
    { id: "kimi-k2.6", name: "Kimi K2.6", contextLength: 131000 },
    { id: "prism", name: "Augment Prism", contextLength: 200000 },
  ],
};
