export default {
  id: "chatgpt-web",
  priority: 236,
  alias: "cgpt-web",
  uiAlias: "cgpt-web",
  display: {
    name: "ChatGPT Web",
    icon: "chat",
    color: "#10A37F",
    textIcon: "CG",
    website: "https://chatgpt.com",
  },
  category: "webCookie",
  authType: "cookie",
  authHint: "Paste the __Secure-next-auth.session-token cookie value from chatgpt.com.",
  serviceKinds: ["llm", "image"],
  transport: {
    baseUrl: "https://chatgpt.com/backend-api/conversation",
    format: "openai",
    executor: "chatgpt-web",
    authType: "cookie",
  },
  models: [
    { id: "gpt-5.5-pro", name: "GPT-5.5 Pro" },
    { id: "gpt-5.5-pro-extended", name: "GPT-5.5 Pro Extended" },
    { id: "gpt-5.5-thinking", name: "GPT-5.5 Thinking" },
    { id: "gpt-5.5", name: "GPT-5.5 Instant" },
    { id: "gpt-5.4-pro", name: "GPT-5.4 Pro" },
    { id: "gpt-5.4-thinking", name: "GPT-5.4 Thinking" },
    { id: "gpt-5.4-thinking-mini", name: "GPT-5.4 Thinking Mini" },
    { id: "gpt-5.3", name: "GPT-5.3 Instant" },
    { id: "gpt-5.3-mini", name: "GPT-5.3 Mini" },
    { id: "o3", name: "o3" },
  ],
  imageConfig: { baseUrl: "https://chatgpt.com/backend-api/conversation" },
};
