export default {
  id: "cohere",
  priority: 90,
  alias: "cohere",
  display: {
    name: "Cohere",
    icon: "hub",
    color: "#39594D",
    textIcon: "CO",
    website: "https://cohere.com",
    notice: {
      apiKeyUrl: "https://dashboard.cohere.com/api-keys",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.cohere.ai/compatibility/v1/chat/completions",
    validateUrl: "https://api.cohere.com/v1/models",
  },
  models: [
    { id: "command-a-plus-05-2026", name: "Command A+ (May 2026)", supportsVision: true },
    { id: "command-a-03-2025", name: "Command A (Mar 2025)" },
    { id: "command-r7b-12-2024", name: "Command R7B (Dec 2024)" },
    { id: "command-a-translate-08-2025", name: "Command A Translate (Aug 2025)" },
    { id: "command-a-reasoning-08-2025", name: "Command A Reasoning (Aug 2025)", supportsReasoning: true },
    { id: "command-a-vision-07-2025", name: "Command A Vision (Jul 2025)", supportsVision: true },
    { id: "command-r-plus-08-2024", name: "Command R+ (Aug 2024)" },
    { id: "command-r-08-2024", name: "Command R (Aug 2024)" },
    { id: "north-small-translate-1-0", name: "North Small Translate 1.0" },
    { id: "north-mini-code-1-0", name: "North Mini Code 1.0" },
    { id: "tiny-aya-global", name: "Tiny Aya Global" },
    { id: "tiny-aya-earth", name: "Tiny Aya Earth" },
    { id: "tiny-aya-fire", name: "Tiny Aya Fire" },
    { id: "tiny-aya-water", name: "Tiny Aya Water" },
    { id: "c4ai-aya-expanse-32b", name: "Aya Expanse 32B" },
    { id: "c4ai-aya-vision-32b", name: "Aya Vision 32B", supportsVision: true },
    { id: "embed-v5.0-pro", name: "Embed v5.0 Pro", kind: "embedding" },
    { id: "embed-v5.0-fast", name: "Embed v5.0 Fast", kind: "embedding" },
    { id: "embed-v4.0", name: "Embed v4.0", kind: "embedding" },
    { id: "rerank-v4.0-pro", name: "Rerank v4.0 Pro", kind: "rerank" },
    { id: "rerank-v4.0-fast", name: "Rerank v4.0 Fast", kind: "rerank" },
    { id: "cohere-transcribe-03-2026", name: "Cohere Transcribe (Mar 2026)", kind: "stt", params: ["language"] },
    { id: "cohere-transcribe-arabic-07-2026", name: "Cohere Transcribe Arabic (Jul 2026)", kind: "stt", params: ["language"] },
    { id: "parse-v5.0", name: "Parse v5.0", kind: "documentParsing" },
  ],
  serviceKinds: ["llm", "embedding", "rerank", "stt", "documentParsing"],
  embeddingConfig: { baseUrl: "https://api.cohere.com/v2/embed", authType: "apikey", authHeader: "bearer" },
  rerankConfig: { baseUrl: "https://api.cohere.com/v2/rerank", authType: "apikey", authHeader: "bearer" },
  sttConfig: { baseUrl: "https://api.cohere.com/v2/audio/transcriptions", authType: "apikey", authHeader: "bearer", format: "cohere-stt" },
};
