export default {
  id: "command-code",
  priority: 100,
  alias: "cmd",
  uiAlias: "cmd",
  display: {
    name: "Command Code",
    icon: "command-code.svg",
    color: "#000000",
    textIcon: "CC",
    website: "https://commandcode.ai",
    notice: {
      text: "Use your Command Code API key from commandcode.ai/studio or the local CLI auth file.",
      apiKeyUrl: "https://commandcode.ai/studio",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.commandcode.ai/alpha/generate",
    format: "commandcode",
    forceStream: true,
    headers: {
      "x-command-code-version": "0.33.2",
      "x-cli-environment": "cli",
    },
  },
  models: [
    { id: "claude-opus-4-7", name: "Claude Opus 4.7 (CC)" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6 (CC)" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6 (CC)" },
    { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5 (CC)" },
    { id: "gpt-5.5", name: "GPT-5.5 (CC)" },
    { id: "gpt-5.4", name: "GPT-5.4 (CC)" },
    { id: "gpt-5.3-codex", name: "GPT-5.3 Codex (CC)" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini (CC)" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro (CC)" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash (CC)" },
    { id: "moonshotai/Kimi-K2.6", name: "Kimi K2.6 (CC)" },
    { id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5 (CC)" },
    { id: "zai-org/GLM-5.1", name: "GLM-5.1 (CC)" },
    { id: "zai-org/GLM-5", name: "GLM-5 (CC)" },
    { id: "MiniMaxAI/MiniMax-M2.7", name: "MiniMax M2.7 (CC)" },
    { id: "MiniMaxAI/MiniMax-M2.5", name: "MiniMax M2.5 (CC)" },
    { id: "Qwen/Qwen3.6-Max-Preview", name: "Qwen 3.6 Max (CC)" },
    { id: "Qwen/Qwen3.6-Plus", name: "Qwen 3.6 Plus (CC)" },
  ],
};
