export default {
  id: "duckduckgo-web",
  priority: 239,
  alias: "ddgw",
  uiAlias: "ddg",
  display: {
    name: "DuckDuckGo AI Chat",
    icon: "travel_explore",
    color: "#DE5833",
    textIcon: "DDG",
    website: "https://duckduckgo.com/aichat",
  },
  category: "free",
  noAuth: true,
  serviceKinds: ["llm"],
  transport: {
    baseUrl: "https://duckduckgo.com/duckchat/v1/chat",
    format: "openai",
    executor: "duckduckgo-web",
    authType: "none",
    noAuth: true,
  },
  models: [
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "gpt-5-mini", name: "GPT-5 Mini" },
    { id: "claude-3-5-haiku-20241022", name: "Claude 3.5 Haiku" },
    { id: "llama-4-scout", name: "Llama 4 Scout" },
    { id: "mistral-small-2501", name: "Mistral Small" },
    { id: "o3-mini", name: "O3 Mini" },
  ],
};
