const models = [
  ["baidu/ERNIE-4.5-VL-424B-A47B-Base-PT", "ERNIE 4.5 VL 424B A47B Base PT", {}],
  ["CohereLabs/c4ai-command-r7b-12-2024", "Command R7B 12-2024", { toolCalling: true }],
  ["CohereLabs/command-a-reasoning-08-2025", "Command A Reasoning 08-2025", { toolCalling: true }],
  ["CohereLabs/command-a-vision-07-2025", "Command A Vision 07-2025", {}],
  ["deepseek-ai/DeepSeek-V4-Pro", "DeepSeek V4 Pro", { toolCalling: true, supportsReasoning: true }],
  ["deepseek-ai/DeepSeek-V4-Flash", "DeepSeek V4 Flash", { toolCalling: true }],
  ["google/gemma-4-31B-it", "Gemma 4 31B", { toolCalling: true }],
  ["google/gemma-4-26B-A4B-it", "Gemma 4 26B A4B", { toolCalling: true }],
  ["inclusionAI/Ling-2.6-1T", "Ling 2.6 1T", { toolCalling: true }],
  ["meta-llama/Llama-4-Scout-17B-16E-Instruct", "Llama 4 Scout 17B 16E Instruct", { toolCalling: true }],
  ["meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", "Llama 4 Maverick 17B 128E Instruct FP8", {}],
  ["MiniMaxAI/MiniMax-M3", "MiniMax M3", { toolCalling: true, supportsReasoning: true }],
  ["moonshotai/Kimi-K2.7-Code", "Kimi K2.7 Code", { toolCalling: true, supportsReasoning: true }],
  ["moonshotai/Kimi-K2.6", "Kimi K2.6", { toolCalling: true }],
  ["nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4", "NVIDIA Nemotron 3 Ultra 550B NVFP4", { toolCalling: true, supportsReasoning: true }],
  ["openai/gpt-oss-120b", "GPT-OSS 120B", { toolCalling: true, supportsReasoning: true }],
  ["openai/gpt-oss-20b", "GPT-OSS 20B", { toolCalling: true, supportsReasoning: true }],
  ["Qwen/Qwen3.5-122B-A10B", "Qwen3.5 122B A10B", { toolCalling: true }],
  ["Qwen/Qwen3.5-397B-A17B", "Qwen3.5 397B A17B", { toolCalling: true }],
  ["Qwen/Qwen3.6-27B", "Qwen3.6 27B", { toolCalling: true }],
  ["Qwen/Qwen3.6-35B-A3B", "Qwen3.6 35B A3B", { toolCalling: true }],
  ["stepfun-ai/Step-3.7-Flash", "Step 3.7 Flash", { toolCalling: true }],
  ["XiaomiMiMo/MiMo-V2.5-Pro", "MiMo V2.5 Pro", { toolCalling: true }],
  ["zai-org/GLM-5.2", "GLM 5.2", { toolCalling: true, supportsReasoning: true }],
].map(([id, name, extra]) => ({ id, name, ...extra }));

export default {
  id: "huggingchat",
  priority: 240,
  alias: "huggingchat",
  uiAlias: "huggingchat",
  display: {
    name: "HuggingChat",
    icon: "chat_bubble",
    color: "#FFD21E",
    textIcon: "HF",
    website: "https://huggingface.co/chat",
  },
  category: "webCookie",
  authType: "cookie",
  authHint: "Paste the full Cookie header from huggingface.co/chat.",
  serviceKinds: ["llm"],
  transport: {
    baseUrl: "https://huggingface.co/chat/conversation",
    format: "openai",
    executor: "huggingchat",
    authType: "cookie",
  },
  models,
};
