export default {
  id: "nanogpt",
  alias: "nanogpt",
  display: {
    name: "NanoGPT",
    icon: "chat",
    color: "#4F46E5",
    textIcon: "NG",
    website: "https://nano-gpt.com",
    notice: {
      apiKeyUrl: "https://nano-gpt.com",
    },
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    baseUrl: "https://nano-gpt.com/api/v1/chat/completions",
    validateUrl: "https://nano-gpt.com/api/v1/models",
    format: "openai",
  },
  models: [
    { id: "chatgpt-4o-latest", name: "ChatGPT 4o Latest" },
    { id: "claude-3.5-sonnet", name: "Claude 3.5 Sonnet" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "auto-model", name: "NanoGPT Auto" },
    { id: "auto-model-basic", name: "NanoGPT Auto Basic" },
    { id: "auto-model-standard", name: "NanoGPT Auto Standard" },
    { id: "auto-model-premium", name: "NanoGPT Auto Premium" },
    { id: "nanogpt/coding-router", name: "NanoGPT Coding Router" },
    { id: "nanogpt/coding-router:low", name: "NanoGPT Coding Router Low" },
    { id: "nanogpt/coding-router:medium", name: "NanoGPT Coding Router Medium" },
    { id: "nanogpt/coding-router:high", name: "NanoGPT Coding Router High" },
    { id: "nanogpt/coding-router:max", name: "NanoGPT Coding Router Max" },
    { id: "claw-low", name: "Claw Low" },
    { id: "claw-medium", name: "Claw Medium" },
    { id: "claw-high", name: "Claw High" },
    { id: "hermes-low", name: "Hermes Low" },
    { id: "hermes-medium", name: "Hermes Medium" },
    { id: "hermes-high", name: "Hermes High" },
    { id: "openai/gpt-6.1-sol", name: "GPT-6.1 Sol" },
    { id: "openai/gpt-6-sol", name: "GPT-6 Sol" },
    { id: "openai/gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "openai/gpt-5.5", name: "GPT-5.5" },
    { id: "anthropic/claude-sonnet-5.5", name: "Claude Sonnet 5.5" },
    { id: "z-ai/glm-5.3-flash", name: "GLM-5.3 Flash" },
    { id: "qwen/qwen3.8-max-prime", name: "Qwen3.8 Max Prime" },
    { id: "qwen/qwen3.8-27b", name: "Qwen3.8 27B" },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra" },
    { id: "nvidia/nemotron-3.5-lightning", name: "Nemotron 3.5 Lightning" },
    { id: "meta/muse-glimmer-30b", name: "Muse Glimmer 30B" },
    { id: "meta/muse-spark-1.3", name: "Muse Spark 1.3" },
    { id: "liquid/lfm-2.5-2.6b", name: "LFM 2.5 2.6B" },
    { id: "longcat-2.0", name: "LongCat 2.0" },
    { id: "typesafe/jev-1.13", name: "Jev 1.13" },
    { id: "fireworks/ember-1", name: "Ember 1" },
  ],
  modelsFetcher: { url: "https://nano-gpt.com/api/v1/models", type: "openai" },
  passthroughModels: true,
  serviceKinds: ["llm"],
};
