export default {
  id: "nimble",
  alias: "nimble",
  aliases: ["nimble-search"],
  display: {
    name: "Nimble",
    icon: "travel_explore",
    color: "#6D28D9",
    textIcon: "NB",
    website: "https://docs.nimbleway.com/nimble-sdk/web-tools/search",
    notice: {
      apiKeyUrl: "https://nimbleway.com",
    },
  },
  category: "apikey",
  authType: "apikey",
  serviceKinds: ["webSearch", "webFetch"],
  searchConfig: {
    baseUrl: "https://sdk.nimbleway.com/v1/search",
    method: "POST",
    authType: "apikey",
    authHeader: "bearer",
    costPerQuery: 0.005,
    freeMonthlyQuota: 0,
    searchTypes: ["web", "news"],
    defaultMaxResults: 5,
    maxMaxResults: 100,
    timeoutMs: 10000,
    cacheTTLMs: 300000,
  },
  fetchConfig: {
    baseUrl: "https://sdk.nimbleway.com/v1/extract",
    method: "POST",
    authType: "apikey",
    authHeader: "bearer",
    costPerQuery: 0.005,
    freeMonthlyQuota: 0,
    formats: ["markdown", "text"],
    maxCharacters: 100000,
    timeoutMs: 15000,
  },
};
