export default {
  id: "opencode-zen",
  priority: 41,
  alias: "opencode-zen",
  // Short alias upstream uses for this provider (port(upstream): #4145); kept
  // as an additional lookup token rather than replacing `alias` so existing
  // "opencode-zen" configs keep working.
  aliases: ["ocz"],
  uiAlias: "ocz",
  display: {
    name: "OpenCode Zen",
    icon: "opencode.svg",
    color: "#6366f1",
    textIcon: "OC",
    website: "https://opencode.ai/zen",
  },
  category: "apikey",
  authType: "apikey",
  authHint: "OpenCode Zen API key. The upstream also exposes rotating free models.",
  transport: {
    baseUrl: "https://opencode.ai/zen/v1/chat/completions",
    format: "openai",
  },
  models: [
    { id: "big-pickle", name: "Big Pickle", supportsReasoning: true, interleavedField: "reasoning_content" },
    { id: "gpt-5-nano", name: "GPT 5 Nano", contextLength: 400000, targetFormat: "openai-responses" },
    { id: "gpt-5", name: "GPT 5", targetFormat: "openai-responses" },
    { id: "gpt-5-codex", name: "GPT 5 Codex", targetFormat: "openai-responses" },
    { id: "gpt-5.1", name: "GPT 5.1", targetFormat: "openai-responses" },
    { id: "gpt-5.1-codex", name: "GPT 5.1 Codex", targetFormat: "openai-responses" },
    { id: "gpt-5.1-codex-max", name: "GPT 5.1 Codex Max", targetFormat: "openai-responses" },
    { id: "gpt-5.1-codex-mini", name: "GPT 5.1 Codex Mini", targetFormat: "openai-responses" },
    { id: "gpt-5.2", name: "GPT 5.2", targetFormat: "openai-responses" },
    { id: "gpt-5.2-codex", name: "GPT 5.2 Codex", targetFormat: "openai-responses" },
    { id: "gpt-5.3-codex", name: "GPT 5.3 Codex", targetFormat: "openai-responses" },
    { id: "gpt-5.3-codex-spark", name: "GPT 5.3 Codex Spark", targetFormat: "openai-responses" },
    { id: "gpt-5.4", name: "GPT 5.4", targetFormat: "openai-responses" },
    { id: "gpt-5.4-mini", name: "GPT 5.4 Mini", targetFormat: "openai-responses" },
    { id: "gpt-5.4-nano", name: "GPT 5.4 Nano", targetFormat: "openai-responses" },
    { id: "gpt-5.4-pro", name: "GPT 5.4 Pro", targetFormat: "openai-responses" },
    { id: "gpt-5.5", name: "GPT 5.5", targetFormat: "openai-responses" },
    { id: "gpt-5.5-pro", name: "GPT 5.5 Pro", targetFormat: "openai-responses" },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5", targetFormat: "claude" },
    { id: "claude-sonnet-4", name: "Claude Sonnet 4", targetFormat: "claude" },
    { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5", targetFormat: "claude" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", targetFormat: "claude" },
    { id: "claude-opus-4-1", name: "Claude Opus 4.1", targetFormat: "claude" },
    { id: "claude-opus-4-5", name: "Claude Opus 4.5", targetFormat: "claude" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6", targetFormat: "claude" },
    { id: "claude-opus-4-7", name: "Claude Opus 4.7", targetFormat: "claude" },
    // Additive catalog entries from port(upstream): #4145. Only ids the
    // existing executor's own model-id regexes already route correctly are
    // added here — see the commit message for what was deferred and why.
    { id: "claude-fable-5", name: "Claude Fable 5", targetFormat: "claude" },
    { id: "claude-fable-5-1", name: "Claude Fable 5.1", targetFormat: "claude" },
    { id: "claude-opus-5", name: "Claude Opus 5", targetFormat: "claude" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", targetFormat: "claude" },
    { id: "gpt-5.6-sol", name: "GPT 5.6 Sol", targetFormat: "openai-responses" },
    { id: "gpt-5.6-terra", name: "GPT 5.6 Terra", targetFormat: "openai-responses" },
    { id: "gpt-5.6-luna", name: "GPT 5.6 Luna", targetFormat: "openai-responses" },
    { id: "grok-build-0.1", name: "Grok Build 0.1" },
    { id: "grok-4.5", name: "Grok 4.5" },
    { id: "grok-4.6", name: "Grok 4.6" },
    { id: "grok-4.7", name: "Grok 4.7" },
    { id: "glm-5", name: "GLM-5" },
    { id: "glm-5.1", name: "GLM-5.1" },
    { id: "glm-5.2", name: "GLM-5.2" },
    { id: "glm-5.3", name: "GLM-5.3" },
    { id: "glm-5.3-flash", name: "GLM-5.3 Flash" },
    { id: "minimax-m3", name: "MiniMax M3", contextLength: 1048576, supportsVision: true },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp" },
    { id: "qwen3.5-plus", name: "Qwen3.5 Plus", targetFormat: "claude", supportsVision: false, strip: ["image"] },
    { id: "qwen3.6-plus", name: "Qwen3.6 Plus", targetFormat: "claude", supportsVision: false, strip: ["image"] },
    { id: "deepseek-v4-flash-free", name: "DeepSeek V4 Flash Free", supportsReasoning: true },
    { id: "minimax-m2.5-free", name: "MiniMax M2.5 Free", contextLength: 204800 },
    { id: "nemotron-3-super-free", name: "Nemotron 3 Super Free", contextLength: 1000000 },
    { id: "qwen3.6-plus-free", name: "Qwen3.6 Plus Free", targetFormat: "claude", contextLength: 200000 },
    // System One (Jev) decision models on the native /systemone endpoint
    { id: "jev-1.13", name: "Jev 1.13", kind: "systemone" },
    { id: "jev-1.13-free", name: "Jev 1.13 Free", kind: "systemone" },
  ],
  serviceKinds: ["llm", "systemone"],
  systemoneConfig: {
    baseUrl: "https://opencode.ai/zen/v1/systemone",
    headers: {
      "x-opencode-client": "desktop",
      "User-Agent": "opencode/1.18.31",
    },
  },
  modelsFetcher: { url: "https://opencode.ai/zen/v1/models", type: "opencode-free" },
  passthroughModels: true,
  features: {
    usage: true,
    usageApikey: true,
  },
};
