export default {
  id: "openai",
  priority: 30,
  alias: "openai",
  display: {
    name: "OpenAI",
    icon: "auto_awesome",
    color: "#10A37F",
    textIcon: "OA",
    website: "https://platform.openai.com",
    notice: {
      apiKeyUrl: "https://platform.openai.com/api-keys",
    },
  },
  category: "apikey",
  thinkingConfig: {
    options: [
      "auto",
      "none",
      "low",
      "medium",
      "high",
    ],
    defaultMode: "auto",
  },
  // GPT-5.6 tool calls with reasoning require the Responses API.
  transport: {
    baseUrl: "https://api.openai.com/v1/chat/completions",
    forceStream: true,
    // Chat accepts the Responses `prompt_cache_key` extension after lowering.
    quirks: { preservePromptCacheKey: true },
  },
  transports: [
    { format: "openai", baseUrl: "https://api.openai.com/v1/chat/completions" },
    { format: "openai-responses", baseUrl: "https://api.openai.com/v1/responses" },
  ],
  models: [
    // Latest text/reasoning models. Responses preserves built-in tool support;
    // Chat Completions remains available where documented by OpenAI.
    { id: "gpt-6-astra", name: "GPT-6 Astra", targetFormat: "openai-responses" },
    { id: "gpt-6.1-sol", name: "GPT-6.1 Sol", targetFormat: "openai-responses" },
    { id: "gpt-6-sol", name: "GPT-6 Sol", targetFormat: "openai-responses" },
    { id: "gpt-6-luna", name: "GPT-6 Luna", targetFormat: "openai-responses" },
    { id: "gpt-5.6", name: "GPT-5.6", targetFormat: "openai-responses" },
    { id: "gpt-5.6-cyber", name: "GPT-5.6 Cyber", targetFormat: "openai-responses" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", targetFormat: "openai-responses" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", targetFormat: "openai-responses" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", targetFormat: "openai-responses" },
    { id: "gpt-5.5", name: "GPT-5.5", targetFormat: "openai-responses" },
    { id: "gpt-5.5-pro", name: "GPT-5.5 Pro", targetFormat: "openai-responses", forceNonStreaming: true },
    { id: "gpt-5.5-pro-2026-04-23", name: "GPT-5.5 Pro (2026-04-23)", targetFormat: "openai-responses", forceNonStreaming: true },
    { id: "gpt-5.5-2026-04-23", name: "GPT-5.5 (2026-04-23)", targetFormat: "openai-responses" },
    { id: "gpt-5.4", name: "GPT-5.4", targetFormat: "openai-responses" },
    { id: "gpt-5.4-2026-03-05", name: "GPT-5.4 (2026-03-05)", targetFormat: "openai-responses" },
    { id: "gpt-5.4-pro", name: "GPT-5.4 Pro", targetFormat: "openai-responses" },
    { id: "gpt-5.4-pro-2026-03-05", name: "GPT-5.4 Pro (2026-03-05)", targetFormat: "openai-responses" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini", targetFormat: "openai-responses" },
    { id: "gpt-5.4-nano", name: "GPT-5.4 Nano", targetFormat: "openai-responses" },
    { id: "gpt-5.4-mini-2026-03-17", name: "GPT-5.4 Mini (2026-03-17)", targetFormat: "openai-responses" },
    { id: "gpt-5.3-codex", name: "GPT-5.3 Codex", targetFormat: "openai-responses" },
    { id: "gpt-5.4-nano-2026-03-17", name: "GPT-5.4 Nano (2026-03-17)", targetFormat: "openai-responses" },
    { id: "gpt-5.2", name: "GPT-5.2", targetFormat: "openai-responses" },
    { id: "gpt-5.2-pro", name: "GPT-5.2 Pro", targetFormat: "openai-responses" },
    { id: "gpt-5.2-pro-2025-12-11", name: "GPT-5.2 Pro (2025-12-11)", targetFormat: "openai-responses" },
    { id: "gpt-5.2-2025-12-11", name: "GPT-5.2 (2025-12-11)", targetFormat: "openai-responses" },
    { id: "gpt-5.1", name: "GPT-5.1", targetFormat: "openai-responses" },
    { id: "gpt-5.1-2025-11-13", name: "GPT-5.1 (2025-11-13)", targetFormat: "openai-responses" },
    { id: "gpt-5", name: "GPT-5", targetFormat: "openai-responses" },
    { id: "gpt-5-2025-08-07", name: "GPT-5 (2025-08-07)", targetFormat: "openai-responses" },
    { id: "gpt-5-pro", name: "GPT-5 Pro", targetFormat: "openai-responses" },
    { id: "gpt-5-pro-2025-10-06", name: "GPT-5 Pro (2025-10-06)", targetFormat: "openai-responses" },
    { id: "gpt-5-mini", name: "GPT-5 Mini", targetFormat: "openai-responses" },
    { id: "gpt-5-mini-2025-08-07", name: "GPT-5 Mini (2025-08-07)", targetFormat: "openai-responses" },
    { id: "gpt-5-nano", name: "GPT-5 Nano", targetFormat: "openai-responses" },
    { id: "gpt-5-nano-2025-08-07", name: "GPT-5 Nano (2025-08-07)", targetFormat: "openai-responses" },
    { id: "gpt-4.1", name: "GPT-4.1" },
    { id: "gpt-4.1-2025-04-14", name: "GPT-4.1 (2025-04-14)" },
    { id: "gpt-4.1-mini", name: "GPT-4.1 Mini" },
    { id: "gpt-4.1-mini-2025-04-14", name: "GPT-4.1 Mini (2025-04-14)" },
    { id: "gpt-4.1-nano", name: "GPT-4.1 Nano" },
    { id: "gpt-4.1-nano-2025-04-14", name: "GPT-4.1 Nano (2025-04-14)" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-2024-05-13", name: "GPT-4o (2024-05-13)" },
    { id: "gpt-4o-2024-08-06", name: "GPT-4o (2024-08-06)" },
    { id: "gpt-4o-2024-11-20", name: "GPT-4o (2024-11-20)" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "gpt-4o-mini-2024-07-18", name: "GPT-4o Mini (2024-07-18)" },
    { id: "gpt-4-turbo", name: "GPT-4 Turbo" },
    { id: "gpt-4-turbo-2024-04-09", name: "GPT-4 Turbo (2024-04-09)" },
    { id: "o3", name: "O3", targetFormat: "openai-responses" },
    { id: "o3-pro", name: "O3 Pro", targetFormat: "openai-responses", forceNonStreaming: true },
    { id: "o4-mini", name: "O4 Mini", targetFormat: "openai-responses" },
    { id: "o4-mini-2025-04-16", name: "O4 Mini (2025-04-16)", targetFormat: "openai-responses" },
    { id: "o3-mini", name: "O3 Mini", targetFormat: "openai-responses" },
    { id: "o3-mini-2025-01-31", name: "O3 Mini (2025-01-31)", targetFormat: "openai-responses" },
    { id: "o1", name: "O1", targetFormat: "openai-responses" },
    { id: "o1-2024-12-17", name: "O1 (2024-12-17)", targetFormat: "openai-responses" },
    { id: "o1-pro", name: "O1 Pro", targetFormat: "openai-responses", forceNonStreaming: true },
    { id: "o1-pro-2025-03-19", name: "O1 Pro (2025-03-19)", targetFormat: "openai-responses", forceNonStreaming: true },
    { id: "gpt-daybreak-blue-latest", name: "Daybreak Blue", targetFormat: "openai-responses" },
    { id: "gpt-daybreak-red-latest", name: "Daybreak Red", targetFormat: "openai-responses" },
    // Approved internal API access exists, but OpenAI publishes no endpoint;
    // chatCore rejects this row until a documented transport is available.
    { id: "gpt-rosalind-research", name: "GPT Rosalind Research", requiresApproval: true, routingUnavailableReason: "Official API access confirmed; endpoint undocumented" },

    { id: "text-embedding-3-large", name: "Text Embedding 3 Large", kind: "embedding" },
    { id: "text-embedding-3-small", name: "Text Embedding 3 Small", kind: "embedding" },
    { id: "text-embedding-ada-002", name: "Text Embedding Ada 002", kind: "embedding" },

    { id: "tts-1", name: "TTS-1", kind: "tts" },
    { id: "tts-1-hd", name: "TTS-1 HD", kind: "tts" },
    { id: "gpt-4o-mini-tts", name: "GPT-4o Mini TTS", kind: "tts" },
    { id: "whisper-1", name: "Whisper 1", params: ["language", "response_format", "temperature", "prompt"], kind: "stt" },
    { id: "gpt-transcribe", name: "GPT Transcribe", kind: "stt" },
    { id: "gpt-4o-transcribe", name: "GPT-4o Transcribe", params: ["language", "response_format", "temperature", "prompt"], kind: "stt" },
    { id: "gpt-4o-mini-transcribe", name: "GPT-4o Mini Transcribe", params: ["language", "response_format", "temperature", "prompt"], kind: "stt" },
    { id: "gpt-4o-transcribe-diarize", name: "GPT-4o Transcribe Diarize", kind: "stt" },

    { id: "gpt-image-2.5-sunburst", name: "GPT Image 2.5 Sunburst", kind: "image" },
    { id: "gpt-image-2.5-sunburst-2026-09-08", name: "GPT Image 2.5 Sunburst (2026-09-08)", kind: "image" },
    { id: "gpt-image-2.5-flare", name: "GPT Image 2.5 Flare", kind: "image" },
    { id: "gpt-image-2.5-flare-2026-09-08", name: "GPT Image 2.5 Flare (2026-09-08)", kind: "image" },
    { id: "gpt-image-2", name: "GPT Image 2", kind: "image" },
    { id: "gpt-image-2-2026-04-21", name: "GPT Image 2 (2026-04-21)", kind: "image" },
    { id: "gpt-image-1.5", name: "GPT Image 1.5", kind: "image" },
    { id: "gpt-image-1-mini", name: "GPT Image 1 Mini", kind: "image" },

    { id: "gpt-image-1", name: "GPT Image 1", kind: "image" },
    { id: "chatgpt-image-latest", name: "ChatGPT Image Latest", kind: "image" },
    { id: "gpt-image-1.5-2025-12-16", name: "GPT Image 1.5 (2025-12-16)", kind: "image" },
    { id: "gpt-audio-1.5", name: "GPT Audio 1.5", kind: "audio", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "gpt-audio", name: "GPT Audio", kind: "audio", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "gpt-audio-2025-08-28", name: "GPT Audio (2025-08-28)", kind: "audio", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "gpt-audio-mini", name: "GPT Audio Mini", kind: "audio", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "gpt-audio-mini-2025-12-15", name: "GPT Audio Mini (2025-12-15)", kind: "audio", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "gpt-realtime-2.1", name: "GPT Realtime 2.1", kind: "realtime" },
    { id: "gpt-realtime-2.1-mini", name: "GPT Realtime 2.1 Mini", kind: "realtime" },
    { id: "gpt-realtime-2", name: "GPT Realtime 2", kind: "realtime" },
    { id: "gpt-realtime-1.5", name: "GPT Realtime 1.5", kind: "realtime" },
    { id: "gpt-realtime", name: "GPT Realtime", kind: "realtime" },
    { id: "gpt-realtime-mini", name: "GPT Realtime Mini", kind: "realtime" },
    { id: "gpt-realtime-translate", name: "GPT Realtime Translate", kind: "realtimeTranslation" },
    { id: "gpt-live-1", name: "GPT Live 1", kind: "live" },
    { id: "gpt-live-transcribe", name: "GPT Live Transcribe", kind: "realtimeTranscription" },
    { id: "gpt-realtime-whisper", name: "GPT Realtime Whisper", kind: "realtimeTranscription" },
    { id: "omni-moderation-latest", name: "Omni Moderation", kind: "moderation" },
    { id: "omni-moderation-2024-09-26", name: "Omni Moderation (2024-09-26)", kind: "moderation" },
  ],
  serviceKinds: ["llm", "embedding", "tts", "stt", "image", "imageToText", "webSearch", "audio", "realtime", "realtimeTranslation", "realtimeTranscription", "live", "moderation"],
  ttsConfig: {
    baseUrl: "https://api.openai.com/v1/audio/speech",
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
    defaultModel: "gpt-4o-mini-tts",
  },
  sttConfig: {
    baseUrl: "https://api.openai.com/v1/audio/transcriptions",
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
  },
  embeddingConfig: { baseUrl: "https://api.openai.com/v1/embeddings", authType: "apikey", authHeader: "bearer" },
  imageConfig: { baseUrl: "https://api.openai.com/v1/images/generations" },
  // WS endpoint and session setup differ by service kind.
  realtimeConfig: {
    wsUrl: "wss://api.openai.com/v1/realtime",
    authHeader: "Authorization",
    authScheme: "Bearer",
    protocols: {
      realtime: { wsUrl: "wss://api.openai.com/v1/realtime", modelInQuery: true },
      live: { wsUrl: "wss://api.openai.com/v1/live/sessions", modelInQuery: true },
      realtimeTranslation: { wsUrl: "wss://api.openai.com/v1/realtime/translations", modelInQuery: true },
      realtimeTranscription: { wsUrl: "wss://api.openai.com/v1/realtime", modelInQuery: false, sessionType: "transcription" },
    },
  },
  searchViaChat: { defaultModel: "gpt-4o-mini", pricingUrl: "https://openai.com/api/pricing" },
};
