export default {
  id: "pollinations",
  priority: 60,
  alias: "pol",
  uiAlias: "pol",
  display: {
    name: "Pollinations",
    icon: "smart_toy",
    color: "#7A4DFF",
    textIcon: "PO",
    website: "https://pollinations.ai",
    notice: {
      text: "Premium Pollinations models require an API key from enter.pollinations.ai; keyless access is limited to the free catalog.",
      apiKeyUrl: "https://enter.pollinations.ai",
    },
  },
  category: "free",
  // The public catalog is keyless; a saved API key unlocks premium models and
  // is preferred when present.
  noAuth: true,
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://gen.pollinations.ai/v1/chat/completions",
    baseUrls: ["https://gen.pollinations.ai/v1/chat/completions"],
    format: "openai",
    noAuth: true,
  },
  models: [
    { id: "openai", name: "OpenAI (Pollinations)" },
    { id: "openai-fast", name: "OpenAI Fast (Pollinations)" },
    { id: "openai-large", name: "OpenAI Large (Pollinations)" },
    { id: "qwen-coder", name: "Qwen Coder (Pollinations)" },
    { id: "mistral", name: "Mistral (Pollinations)" },
    { id: "gemini", name: "Gemini (Pollinations)", requiresApiKey: true },
    { id: "gemini-flash-lite-3.1", name: "Gemini Flash Lite 3.1 (Pollinations)" },
    { id: "gemini-fast", name: "Gemini Fast (Pollinations)", requiresApiKey: true },
    { id: "deepseek", name: "DeepSeek (Pollinations)" },
    { id: "grok", name: "Grok (Pollinations)" },
    { id: "grok-large", name: "Grok Large (Pollinations)" },
    { id: "gemini-search", name: "Gemini Search (Pollinations)" },
    { id: "midijourney", name: "Midijourney (Pollinations)", requiresApiKey: true },
    { id: "midijourney-large", name: "Midijourney Large (Pollinations)", requiresApiKey: true },
    { id: "claude-fast", name: "Claude Fast (Pollinations)", requiresApiKey: true },
    { id: "claude", name: "Claude (Pollinations)", requiresApiKey: true },
    { id: "claude-large", name: "Claude Large (Pollinations)", requiresApiKey: true },
    { id: "perplexity-fast", name: "Perplexity Fast (Pollinations)" },
    { id: "perplexity-reasoning", name: "Perplexity Reasoning (Pollinations)" },
    { id: "kimi", name: "Kimi (Pollinations)" },
    { id: "gemini-large", name: "Gemini Large (Pollinations)" },
    { id: "nova-fast", name: "Nova Fast (Pollinations)" },
    { id: "nova", name: "Nova (Pollinations)" },
    { id: "glm", name: "GLM (Pollinations)" },
    { id: "minimax", name: "MiniMax (Pollinations)" },
    { id: "mistral-large", name: "Mistral Large (Pollinations)" },
    { id: "polly", name: "Polly (Pollinations)" },
    { id: "qwen-coder-large", name: "Qwen Coder Large (Pollinations)" },
    { id: "qwen-large", name: "Qwen Large (Pollinations)" },
    { id: "qwen-vision", name: "Qwen Vision (Pollinations)" },
    { id: "qwen-safety", name: "Qwen Safety (Pollinations)" },
  ],
};
