export default {
  id: "qwen-cloud",
  alias: "qwc",
  display: {
    name: "Qwen Cloud",
    icon: "cloud",
    color: "#615CED",
    textIcon: "QC",
    website: "https://www.qwencloud.com/",
    notice: {
      text: "Use a Qwen Cloud API key and select its Global or Beijing region.",
      apiKeyUrl: "https://dashscope.console.aliyun.com",
    },
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions",
    validateUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/models",
    format: "openai",
  },
  models: [
    { id: "qwen3.8-max", name: "Qwen3.8 Max" },
    { id: "qwen3.7-max-2026-06-08", name: "Qwen3.7 Max (2026-06-08)" },
    { id: "qwen3.7-plus", name: "Qwen3.7 Plus" },
    { id: "qwen3.6-plus", name: "Qwen3.6 Plus" },
    { id: "qwen3.6-27b", name: "Qwen3.6 27B" },
    { id: "qwen3.6-35b-a3b", name: "Qwen3.6 35B A3B" },
    { id: "qwen3.5-plus-2026-04-20", name: "Qwen3.5 Plus (2026-04-20)" },
    { id: "qwen3.5-122b-a10b", name: "Qwen3.5 122B A10B" },
    { id: "qwen3.5-397b-a17b", name: "Qwen3.5 397B A17B" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "glm-5.2-fast-preview", name: "GLM 5.2 Fast Preview" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
  ],
  modelsFetcher: { url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/models", type: "openai" },
  passthroughModels: true,
  serviceKinds: ["llm"],
};
