export default {
  id: "together",
  priority: 60,
  alias: "together",
  display: {
    name: "Together AI",
    icon: "group_work",
    color: "#0F6FFF",
    textIcon: "TG",
    website: "https://www.together.ai",
    notice: { apiKeyUrl: "https://api.together.xyz/settings/api-keys" },
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    baseUrl: "https://api.together.xyz/v1/chat/completions",
    validateUrl: "https://api.together.xyz/v1/models",
  },
  models: [
    { id: "thinkingmachines/Inkling", name: "Inkling", contextLength: 524288 },
    { id: "MiniMaxAI/MiniMax-M3", name: "MiniMax M3", kind: "imageToText", contextLength: 524288, inputModalities: ["text", "image"] },
    { id: "Qwen/Qwen3.8-2.4T-A95B", name: "Qwen3.8 2.4T A95B" },
    { id: "Qwen/Qwen3.7-Max", name: "Qwen3.7 Max" },
    { id: "Qwen/Qwen3.6-Plus", name: "Qwen3.6 Plus", contextLength: 1000000 },
    { id: "Qwen/Qwen3.5-9B", name: "Qwen3.5 9B", kind: "imageToText", contextLength: 262144, inputModalities: ["text", "image"] },
    { id: "moonshotai/Kimi-K3", name: "Kimi K3", kind: "imageToText", contextLength: 1048576, inputModalities: ["text", "image"] },
    { id: "zai-org/GLM-5.3", name: "GLM 5.3", contextLength: 1048575 },
    { id: "zai-org/GLM-5.3-Flash", name: "GLM 5.3 Flash", contextLength: 1048575 },
    { id: "zai-org/GLM-5.2", name: "GLM 5.2", contextLength: 1048575 },
    { id: "openai/gpt-oss-120b", name: "GPT-OSS 120B", contextLength: 131072 },
    { id: "deepseek-ai/DeepSeek-V4-Flash-0731", name: "DeepSeek V4 Flash", contextLength: 1048576 },
    { id: "deepseek-ai/DeepSeek-V4-Pro-0813", name: "DeepSeek V4 Pro", contextLength: 1048576 },
    { id: "meta-llama/Llama-3.3-70B-Instruct-Turbo", name: "Llama 3.3 70B Turbo", contextLength: 131072 },
    { id: "Qwen/Qwen3.7-Plus", name: "Qwen3.7 Plus", contextLength: 1000000 },
    { id: "Prism-ML/Ternary-Bonsai-27B", name: "Ternary Bonsai 27B", contextLength: 262144 },
    { id: "meta-models/Muse-Glimmer-30B", name: "Muse Glimmer 30B", contextLength: 131072 },
    { id: "Qwen/Qwen3.8-Flash", name: "Qwen3.8 Flash", contextLength: 1000000 },
    { id: "deepseek-ai/DeepSeek-V4.1-Flash", name: "DeepSeek V4.1 Flash", contextLength: 1000000 },
    { id: "together/Tev1-4B-experimental", name: "Tev1 4B Experimental", contextLength: 32768 },
    { id: "deepseek-ai/DeepSeek-R1", name: "DeepSeek R1" },
    { id: "Qwen/Qwen3-235B-A22B", name: "Qwen3 235B" },
    { id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", name: "Llama 4 Maverick" },
    { id: "google/flash-image-2.5", name: "Flash Image 2.5", kind: "image" },
    { id: "google/gemini-3-pro-image", name: "Gemini 3 Pro Image", kind: "image" },
    { id: "black-forest-labs/FLUX.1.1-pro", name: "FLUX 1.1 Pro", kind: "image" },
    { id: "black-forest-labs/FLUX.1-kontext-pro", name: "FLUX.1 Kontext Pro", kind: "image" },
    { id: "black-forest-labs/FLUX.1-kontext-max", name: "FLUX.1 Kontext Max", kind: "image" },
    { id: "black-forest-labs/FLUX.2-pro", name: "FLUX.2 Pro", kind: "image" },
    { id: "black-forest-labs/FLUX.2-dev", name: "FLUX.2 Dev", kind: "image" },
    { id: "black-forest-labs/FLUX.2-flex", name: "FLUX.2 Flex", kind: "image" },
    { id: "ByteDance-Seed/Seedream-3.0", name: "Seedream 3.0", kind: "image" },
    { id: "ByteDance-Seed/Seedream-4.0", name: "Seedream 4.0", kind: "image" },
    { id: "ByteDance/Seedream-5.0-lite", name: "Seedream 5.0 Lite", kind: "image" },
    { id: "Qwen/Qwen-Image", name: "Qwen Image", kind: "image" },
    { id: "RunDiffusion/Juggernaut-pro-flux", name: "Juggernaut Pro Flux", kind: "image" },
    { id: "Rundiffusion/Juggernaut-Lightning-Flux", name: "Juggernaut Lightning Flux", kind: "image" },
    { id: "ideogram/ideogram-3.0", name: "Ideogram 3.0", kind: "image" },
    { id: "stabilityai/stable-diffusion-xl-base-1.0", name: "SD XL", kind: "image" },
    { id: "black-forest-labs/FLUX.2-max", name: "FLUX.2 Max", kind: "image" },
    { id: "google/flash-image-3.1", name: "Gemini 3.1 Flash Image", kind: "image" },
    { id: "openai/gpt-image-1.5", name: "GPT Image 1.5", kind: "image" },
    { id: "Qwen/Qwen-Image-2.0", name: "Qwen Image 2.0", kind: "image" },
    { id: "Qwen/Qwen-Image-2.0-Pro", name: "Qwen Image 2.0 Pro", kind: "image" },
    { id: "Wan-AI/Wan2.6-image", name: "Wan 2.6 Image", kind: "image" },
    { id: "ideogram/ideogram-4.0", name: "Ideogram 4.0", kind: "image" },
    { id: "openai/gpt-image-2", name: "GPT Image 2", kind: "image" },
    { id: "google/flash-image-3.1-lite", name: "Gemini 3.1 Flash Lite Image", kind: "image" },
    { id: "prunaai/p-image-ideogram", name: "P-Image-Ideogram", kind: "image" },
    { id: "minimax/video-01-director", name: "MiniMax 01 Director", kind: "video" },
    { id: "minimax/hailuo-02", name: "MiniMax Hailuo 02", kind: "video" },
    { id: "ByteDance/Seedance-1.0-pro", name: "Seedance 1.0 Pro", kind: "video" },
    { id: "pixverse/pixverse-v5", name: "PixVerse v5", kind: "video" },
    { id: "vidu/vidu-q1", name: "Vidu Q1", kind: "video" },
    { id: "pixverse/pixverse-v5.6", name: "PixVerse v5.6", kind: "video" },
    { id: "Wan-AI/wan2.7-t2v", name: "Wan 2.7 T2V", kind: "video" },
    { id: "vidu/vidu-q3", name: "Vidu Q3", kind: "video" },
    { id: "vidu/vidu-q3-turbo", name: "Vidu Q3 Turbo", kind: "video" },
    { id: "Wan-AI/wan2.7-i2v", name: "Wan 2.7 I2V", kind: "video" },
    { id: "Wan-AI/wan2.7-r2v", name: "Wan 2.7 R2V", kind: "video" },
    { id: "pixverse/pixverse-v6", name: "PixVerse v6", kind: "video" },
    { id: "alibaba/happyhorse-1.0-t2v", name: "HappyHorse 1.0 T2V", kind: "video" },
    { id: "ByteDance/Seedance-2.0", name: "Seedance 2.0", kind: "video" },
    { id: "alibaba/happyhorse-1.0-i2v", name: "HappyHorse 1.0 I2V", kind: "video" },
    { id: "alibaba/happyhorse-1.0-r2v", name: "HappyHorse 1.0 R2V", kind: "video" },
    { id: "google/veo-3.1", name: "Veo 3.1", kind: "video" },
    { id: "google/veo-3.1-lite", name: "Veo 3.1 Lite", kind: "video" },
    { id: "alibaba/happyhorse-1.1-i2v", name: "HappyHorse 1.1 I2V", kind: "video" },
    { id: "alibaba/happyhorse-1.1-r2v", name: "HappyHorse 1.1 R2V", kind: "video" },
    { id: "alibaba/happyhorse-1.1-t2v", name: "HappyHorse 1.1 T2V", kind: "video" },
    { id: "black-forest-labs/FLUX-3", name: "FLUX 3", kind: "video" },
    { id: "ByteDance/Seedance-2.5", name: "Seedance 2.5", kind: "video" },
    { id: "ByteDance/Seedance-1.0-lite", name: "Seedance 1.0 Lite", kind: "video" },
    { id: "MiniMaxAI/MiniMax-H3", name: "MiniMax H3", kind: "video" },
    { id: "canopylabs/orpheus-3b-0.1-ft", name: "Orpheus 3B", kind: "tts" },
    { id: "hexgrad/Kokoro-82M", name: "Kokoro", kind: "tts" },
    { id: "cartesia/sonic-3", name: "Cartesia Sonic 3", kind: "tts" },
    { id: "cartesia/sonic-2", name: "Cartesia Sonic 2", kind: "tts" },
    { id: "cartesia/sonic", name: "Cartesia Sonic", kind: "tts" },
    { id: "openai/whisper-large-v3", name: "Whisper Large v3", kind: "stt" },
    { id: "nvidia/parakeet-tdt-0.6b-v3", name: "Parakeet TDT 0.6B v3", kind: "stt" },
    { id: "nvidia/nemotron-3-asr-streaming-0.6b", name: "Nemotron 3 ASR Streaming", kind: "stt" },
    { id: "nvidia/nemotron-3.5-asr-streaming-0.6b", name: "Nemotron 3.5 ASR Streaming", kind: "stt" },
  ],
  serviceKinds: ["llm", "imageToText", "image", "video", "tts", "stt"],
  imageConfig: { baseUrl: "https://api.together.ai/v1/images/generations" },
  videoConfig: {
    format: "together",
    createUrl: "https://api.together.ai/v2/videos",
    queryUrl: "https://api.together.ai/v2/videos",
    defaultModel: "minimax/video-01-director",
  },
  ttsConfig: { baseUrl: "https://api.together.ai/v1/audio/speech", authType: "apikey", authHeader: "bearer", format: "openai" },
  sttConfig: { baseUrl: "https://api.together.ai/v1/audio/transcriptions", authType: "apikey", authHeader: "bearer", format: "openai", translationModels: ["openai/whisper-large-v3"] },
};
