export default {
  id: "zai",
  alias: "zai",
  display: {
    name: "Z.AI",
    icon: "psychology",
    color: "#2563EB",
    textIcon: "ZA",
    website: "https://open.bigmodel.cn",
    notice: {
      apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.z.ai/api/anthropic/v1/messages",
    format: "claude",
    urlSuffix: "?beta=true",
    headers: {
      "Anthropic-Version": "2023-06-01",
      "Anthropic-Beta": "claude-code-20250219,interleaved-thinking-2025-05-14",
    },
    auth: {
      combined: true,
      header: "x-api-key",
      scheme: "raw",
    },
  },
  models: [
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "glm-5-turbo", name: "GLM 5 Turbo" },
    { id: "glm-4.7-flash", name: "GLM 4.7 Flash (Free)", free: true },
    { id: "glm-4.7", name: "GLM 4.7" },
    { id: "glm-4.7-flashx", name: "GLM 4.7 FlashX" },
    { id: "glm-4.6", name: "GLM 4.6" },
    { id: "glm-4.5", name: "GLM 4.5" },
    { id: "glm-4.5-x", name: "GLM 4.5 X" },
    { id: "glm-4.5-air", name: "GLM 4.5 Air" },
    { id: "glm-4.5-airx", name: "GLM 4.5 AirX" },
    { id: "glm-4-32b-0414-128k", name: "GLM 4 32B 0414 128K" },
    { id: "glm-4.5-flash", name: "GLM 4.5 Flash (Free)", free: true },
  ],
};
