export default {
  id: "zenmux-free",
  priority: 225,
  alias: "zmf",
  uiAlias: "zmf",
  display: {
    name: "ZenMux Free",
    icon: "auto_awesome",
    color: "#6D5EF6",
    textIcon: "ZF",
    website: "https://zenmux.ai",
  },
  category: "webCookie",
  authType: "cookie",
  authHint: "Paste the full Cookie header from zenmux.ai. It must include ctoken=...",
  transport: {
    baseUrl: "https://zenmux.ai/api/anthropic/v1/messages",
    format: "openai",
    executor: "zenmux-free",
    authType: "cookie",
  },
  models: [
    { id: "deepseek/deepseek-chat", name: "DeepSeek V3.2 (Non-thinking)", capabilities: { tools: false } },
    { id: "deepseek/deepseek-reasoner", name: "DeepSeek V3.2 (Thinking)", supportsReasoning: true, capabilities: { tools: false } },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro", supportsReasoning: true, capabilities: { tools: false } },
    { id: "kuaishou/kat-coder-pro-v1-free", name: "KAT Coder Pro V1 Free", capabilities: { tools: false } },
    { id: "z-ai/glm-4.7-flash-free", name: "GLM 4.7 Flash Free", capabilities: { tools: false } },
    { id: "stepfun/step-3.5-flash-free", name: "Step 3.5 Flash Free", capabilities: { tools: false } },
    { id: "inclusionai/ling-1t", name: "Ling 1T", capabilities: { tools: false } },
    { id: "inclusionai/ling-mini-2.0", name: "Ling Mini 2.0", capabilities: { tools: false } },
    { id: "inclusionai/ring-1t", name: "Ring 1T", capabilities: { tools: false } },
    { id: "sapiens-ai/agnes-1.5-lite", name: "Agnes 1.5 Lite", capabilities: { tools: false } },
    { id: "sapiens-ai/agnes-1.5-pro", name: "Agnes 1.5 Pro", capabilities: { tools: false } },
  ],
};
