// AUTO-GENERATED by scripts/migrate-sqlite-ddl-to-pg.mjs — do not edit.
// Equivalent of the SQLite 001-initial.js in PG dialect. The bootstrap
// creates every table declared in `src/lib/db/schema.js` using the PG DDL
// translator.

import { TABLES } from "../../schema.js";
import { translateCreateTable } from "../../dialects/postgres/translate.js";

const migration = {
  version: 1,
  name: "initial",
  up(adapter) {
    adapter.exec(
      `CREATE TABLE IF NOT EXISTS _meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)`
    );
    for (const [name, def] of Object.entries(TABLES)) {
      const { createSql, indexSqls } = translateCreateTable(name, def);
      adapter.exec(createSql);
      for (const idx of indexSqls) adapter.exec(idx);
    }
  },
};

export default migration;
