/**
 * Durin DS — Console Log page mock data.
 *
 * Realistic server-side log stream emitted by the gateway. Each line is a
 * typed envelope so the page can colorize by level without re-parsing the
 * payload. Counts (~200 lines worth) and timestamps are anchored to a
 * single session window so the toolbar's `200/200` indicator is stable.
 */

const SESSION_START = new Date("2026-09-01T17:48:00Z");

function offsetSeconds(seconds) {
  const stamp = new Date(SESSION_START.getTime() + seconds * 1000);
  const hh = String(stamp.getUTCHours()).padStart(2, "0");
  const mm = String(stamp.getUTCMinutes()).padStart(2, "0");
  const ss = String(stamp.getUTCSeconds()).padStart(2, "0");
  return `${hh}:${mm}:${ss}`;
}

/**
 * Log line schema:
 *   { ts, level, icon?, tag, message, meta? }
 *
 * Levels: "info" | "warn" | "error" | "success"
 * `icon` is an inline Material Symbols ligature shown before the message for
 * warning/danger lines (plain text otherwise).
 * `tag` is a short all-caps facet (TIER, ROUTE, HEADROOM, …) so the page can
 * optionally colorize it. It is plain text — no HTML.
 */
export const LOG_LINES = [
  { ts: offsetSeconds(0),   level: "info",    tag: "BOOT",   message: "durindoor gateway v2.1.3 starting (commit 8e2a91f)" },
  { ts: offsetSeconds(0),   level: "info",    tag: "CONFIG", message: "loaded providers.yml — 14 providers, 23 models" },
  { ts: offsetSeconds(1),   level: "info",    tag: "ROUTE",  message: "registered /v1/chat/completions, /v1/responses, /v1/messages" },
  { ts: offsetSeconds(1),   level: "success", tag: "READY",  message: "listening on :20128 (tunnel: tim-rpg.trycloudflare.com)" },
  { ts: offsetSeconds(2),   level: "info",    tag: "TIER",   message: "CODEX tier bound to gpt-5.6-sol, cc/claude-fable-5" },
  { ts: offsetSeconds(3),   level: "info",    tag: "TIER",   message: "CORTEX tier bound to codex/gpt-5.6, anthropic/claude-fable-5" },
  { ts: offsetSeconds(3),   level: "info",    tag: "HEADROOM", message: "compression proxy online at :11435, 92% headroom remaining" },
  { ts: offsetSeconds(14),  level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-9" },
  { ts: offsetSeconds(14),  level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(15),  level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 412 tok — 4.2k tok/s" },
  { ts: offsetSeconds(15),  level: "success", tag: "DONE",   message: "200 OK in 1.84s — 412 prompt + 318 completion tokens, $0.00412" },
  { ts: offsetSeconds(18),  level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-1" },
  { ts: offsetSeconds(19),  level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 24ms" },
  { ts: offsetSeconds(20),  level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 1,082 tok — 6.8k tok/s" },
  { ts: offsetSeconds(21),  level: "success", tag: "DONE",   message: "200 OK in 3.62s — 128 prompt + 1,082 completion tokens, $0.00931" },
  { ts: offsetSeconds(28),  level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(29),  level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 16ms" },
  { ts: offsetSeconds(30),  level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 256 tok — 5.1k tok/s" },
  { ts: offsetSeconds(31),  level: "success", tag: "DONE",   message: "200 OK in 1.21s — 88 prompt + 256 completion tokens, $0.00188" },
  { ts: offsetSeconds(40),  level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-4" },
  { ts: offsetSeconds(41),  level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 22ms" },
  { ts: offsetSeconds(42),  level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 712 tok — 5.9k tok/s" },
  { ts: offsetSeconds(43),  level: "success", tag: "DONE",   message: "200 OK in 2.04s — 256 prompt + 712 completion tokens, $0.00564" },
  { ts: offsetSeconds(52),  level: "info",    tag: "POST",   message: "/v1/responses stream=200 model=gpt-5.6-sol  key=key-9" },
  { ts: offsetSeconds(53),  level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 19ms" },
  { ts: offsetSeconds(54),  level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 318 tok — 4.4k tok/s" },
  { ts: offsetSeconds(55),  level: "success", tag: "DONE",   message: "200 OK in 1.62s — 412 prompt + 318 completion tokens, $0.00412" },
  { ts: offsetSeconds(63),  level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-7" },
  { ts: offsetSeconds(64),  level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 17ms" },
  { ts: offsetSeconds(65),  level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 148 tok — 3.1k tok/s" },
  { ts: offsetSeconds(66),  level: "warn",    icon: "warning", tag: "TIER", message: "[TIER] CODEX | gpt-5.6-sol backoff 800ms — upstream slow window" },
  { ts: offsetSeconds(67),  level: "success", tag: "DONE",   message: "200 OK in 2.31s — 96 prompt + 148 completion tokens, $0.00196" },
  { ts: offsetSeconds(74),  level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-3" },
  { ts: offsetSeconds(75),  level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 21ms" },
  { ts: offsetSeconds(76),  level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 902 tok — 6.2k tok/s" },
  { ts: offsetSeconds(77),  level: "success", tag: "DONE",   message: "200 OK in 2.84s — 198 prompt + 902 completion tokens, $0.00780" },
  { ts: offsetSeconds(86),  level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(87),  level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(88),  level: "warn",    icon: "warning", tag: "HEADROOM", message: "headroom 38% — compression ratio 2.4× above soft limit" },
  { ts: offsetSeconds(89),  level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 204 tok — 4.7k tok/s" },
  { ts: offsetSeconds(90),  level: "success", tag: "DONE",   message: "200 OK in 1.42s — 142 prompt + 204 completion tokens, $0.00274" },
  { ts: offsetSeconds(98),  level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-1" },
  { ts: offsetSeconds(99),  level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 23ms" },
  { ts: offsetSeconds(100), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 1,184 tok — 7.1k tok/s" },
  { ts: offsetSeconds(101), level: "success", tag: "DONE",   message: "200 OK in 3.91s — 224 prompt + 1,184 completion tokens, $0.01032" },
  { ts: offsetSeconds(112), level: "info",    tag: "POST",   message: "/v1/images/generations model=imagen-4-fast  key=key-12" },
  { ts: offsetSeconds(113), level: "info",    tag: "TIER",   message: "[TIER] MEDIA | imagen-4-fast routed in 31ms" },
  { ts: offsetSeconds(115), level: "info",    tag: "TIER",   message: "[TIER] MEDIA | image 1024×1024 generated in 1.84s" },
  { ts: offsetSeconds(116), level: "success", tag: "DONE",   message: "200 OK in 1.84s — 1 image, $0.01200" },
  { ts: offsetSeconds(124), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-5" },
  { ts: offsetSeconds(125), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 19ms" },
  { ts: offsetSeconds(126), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 312 tok — 4.9k tok/s" },
  { ts: offsetSeconds(127), level: "warn",    icon: "warning", tag: "TIER", message: "[TIER] CODEX | client disconnected before stream end" },
  { ts: offsetSeconds(128), level: "error",   icon: "cancel",  tag: "CANCELLED", message: "request aborted — client closed connection after 1.18s" },
  { ts: offsetSeconds(136), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-4" },
  { ts: offsetSeconds(137), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 25ms" },
  { ts: offsetSeconds(138), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 642 tok — 5.5k tok/s" },
  { ts: offsetSeconds(139), level: "success", tag: "DONE",   message: "200 OK in 1.93s — 184 prompt + 642 completion tokens, $0.00518" },
  { ts: offsetSeconds(148), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(149), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 16ms" },
  { ts: offsetSeconds(150), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 268 tok — 5.2k tok/s" },
  { ts: offsetSeconds(151), level: "success", tag: "DONE",   message: "200 OK in 1.27s — 104 prompt + 268 completion tokens, $0.00206" },
  { ts: offsetSeconds(160), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-3" },
  { ts: offsetSeconds(161), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 21ms" },
  { ts: offsetSeconds(162), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 824 tok — 6.4k tok/s" },
  { ts: offsetSeconds(163), level: "success", tag: "DONE",   message: "200 OK in 2.41s — 212 prompt + 824 completion tokens, $0.00712" },
  { ts: offsetSeconds(172), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-9" },
  { ts: offsetSeconds(173), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(174), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 412 tok — 4.4k tok/s" },
  { ts: offsetSeconds(175), level: "success", tag: "DONE",   message: "200 OK in 1.74s — 388 prompt + 412 completion tokens, $0.00412" },
  { ts: offsetSeconds(184), level: "info",    tag: "POST",   message: "/v1/audio/speech model=gpt-4o-mini-tts  key=key-11" },
  { ts: offsetSeconds(185), level: "info",    tag: "TIER",   message: "[TIER] MEDIA | gpt-4o-mini-tts routed in 28ms" },
  { ts: offsetSeconds(186), level: "info",    tag: "TIER",   message: "[TIER] MEDIA | synthesized 14.2s of speech in 0.92s" },
  { ts: offsetSeconds(187), level: "success", tag: "DONE",   message: "200 OK in 0.92s — 14.2s audio, $0.00284" },
  { ts: offsetSeconds(196), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-5" },
  { ts: offsetSeconds(197), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 19ms" },
  { ts: offsetSeconds(198), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 188 tok — 3.8k tok/s" },
  { ts: offsetSeconds(199), level: "success", tag: "DONE",   message: "200 OK in 1.08s — 72 prompt + 188 completion tokens, $0.00158" },
  { ts: offsetSeconds(208), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-1" },
  { ts: offsetSeconds(209), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 24ms" },
  { ts: offsetSeconds(210), level: "warn",    icon: "warning", tag: "HEADROOM", message: "headroom 14% — compression ratio 3.1× above soft limit" },
  { ts: offsetSeconds(210), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 942 tok — 6.7k tok/s" },
  { ts: offsetSeconds(211), level: "success", tag: "DONE",   message: "200 OK in 2.78s — 232 prompt + 942 completion tokens, $0.00822" },
  { ts: offsetSeconds(220), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(221), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(222), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 256 tok — 4.6k tok/s" },
  { ts: offsetSeconds(223), level: "success", tag: "DONE",   message: "200 OK in 1.34s — 96 prompt + 256 completion tokens, $0.00196" },
  { ts: offsetSeconds(232), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-4" },
  { ts: offsetSeconds(233), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 22ms" },
  { ts: offsetSeconds(234), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 712 tok — 5.9k tok/s" },
  { ts: offsetSeconds(235), level: "success", tag: "DONE",   message: "200 OK in 2.05s — 256 prompt + 712 completion tokens, $0.00564" },
  { ts: offsetSeconds(244), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-7" },
  { ts: offsetSeconds(245), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 17ms" },
  { ts: offsetSeconds(246), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 148 tok — 3.2k tok/s" },
  { ts: offsetSeconds(247), level: "warn",    icon: "warning", tag: "TIER", message: "[TIER] CODEX | gpt-5.6-sol backoff 1.2s — upstream slow window" },
  { ts: offsetSeconds(248), level: "success", tag: "DONE",   message: "200 OK in 2.62s — 96 prompt + 148 completion tokens, $0.00196" },
  { ts: offsetSeconds(256), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-3" },
  { ts: offsetSeconds(257), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 21ms" },
  { ts: offsetSeconds(258), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 902 tok — 6.3k tok/s" },
  { ts: offsetSeconds(259), level: "success", tag: "DONE",   message: "200 OK in 2.81s — 198 prompt + 902 completion tokens, $0.00780" },
  { ts: offsetSeconds(268), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(269), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(270), level: "warn",    icon: "warning", tag: "HEADROOM", message: "headroom 11% — compression ratio 3.4× above soft limit" },
  { ts: offsetSeconds(270), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 204 tok — 4.8k tok/s" },
  { ts: offsetSeconds(271), level: "success", tag: "DONE",   message: "200 OK in 1.42s — 142 prompt + 204 completion tokens, $0.00274" },
  { ts: offsetSeconds(280), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-1" },
  { ts: offsetSeconds(281), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 23ms" },
  { ts: offsetSeconds(282), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 1,184 tok — 7.1k tok/s" },
  { ts: offsetSeconds(283), level: "success", tag: "DONE",   message: "200 OK in 3.91s — 224 prompt + 1,184 completion tokens, $0.01032" },
  { ts: offsetSeconds(292), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-5" },
  { ts: offsetSeconds(293), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 19ms" },
  { ts: offsetSeconds(294), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 312 tok — 4.9k tok/s" },
  { ts: offsetSeconds(295), level: "warn",    icon: "warning", tag: "TIER", message: "[TIER] CODEX | client disconnected before stream end" },
  { ts: offsetSeconds(296), level: "error",   icon: "cancel",  tag: "CANCELLED", message: "request aborted — client closed connection after 1.04s" },
  { ts: offsetSeconds(304), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-4" },
  { ts: offsetSeconds(305), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 25ms" },
  { ts: offsetSeconds(306), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 642 tok — 5.5k tok/s" },
  { ts: offsetSeconds(307), level: "success", tag: "DONE",   message: "200 OK in 1.93s — 184 prompt + 642 completion tokens, $0.00518" },
  { ts: offsetSeconds(316), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(317), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 16ms" },
  { ts: offsetSeconds(318), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 268 tok — 5.2k tok/s" },
  { ts: offsetSeconds(319), level: "success", tag: "DONE",   message: "200 OK in 1.27s — 104 prompt + 268 completion tokens, $0.00206" },
  { ts: offsetSeconds(328), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-3" },
  { ts: offsetSeconds(329), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 21ms" },
  { ts: offsetSeconds(330), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 824 tok — 6.4k tok/s" },
  { ts: offsetSeconds(331), level: "success", tag: "DONE",   message: "200 OK in 2.41s — 212 prompt + 824 completion tokens, $0.00712" },
  { ts: offsetSeconds(340), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-9" },
  { ts: offsetSeconds(341), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(342), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 412 tok — 4.4k tok/s" },
  { ts: offsetSeconds(343), level: "success", tag: "DONE",   message: "200 OK in 1.74s — 388 prompt + 412 completion tokens, $0.00412" },
  { ts: offsetSeconds(352), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-5" },
  { ts: offsetSeconds(353), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 19ms" },
  { ts: offsetSeconds(354), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 188 tok — 3.8k tok/s" },
  { ts: offsetSeconds(355), level: "success", tag: "DONE",   message: "200 OK in 1.08s — 72 prompt + 188 completion tokens, $0.00158" },
  { ts: offsetSeconds(364), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-1" },
  { ts: offsetSeconds(365), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 24ms" },
  { ts: offsetSeconds(366), level: "warn",    icon: "warning", tag: "HEADROOM", message: "headroom 9% — compression ratio 3.6× above soft limit" },
  { ts: offsetSeconds(366), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 942 tok — 6.7k tok/s" },
  { ts: offsetSeconds(367), level: "success", tag: "DONE",   message: "200 OK in 2.78s — 232 prompt + 942 completion tokens, $0.00822" },
  { ts: offsetSeconds(376), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(377), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(378), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 256 tok — 4.6k tok/s" },
  { ts: offsetSeconds(379), level: "success", tag: "DONE",   message: "200 OK in 1.34s — 96 prompt + 256 completion tokens, $0.00196" },
  { ts: offsetSeconds(388), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-4" },
  { ts: offsetSeconds(389), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 22ms" },
  { ts: offsetSeconds(390), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 712 tok — 5.9k tok/s" },
  { ts: offsetSeconds(391), level: "success", tag: "DONE",   message: "200 OK in 2.05s — 256 prompt + 712 completion tokens, $0.00564" },
  { ts: offsetSeconds(400), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-7" },
  { ts: offsetSeconds(401), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 17ms" },
  { ts: offsetSeconds(402), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 148 tok — 3.2k tok/s" },
  { ts: offsetSeconds(403), level: "warn",    icon: "warning", tag: "TIER", message: "[TIER] CODEX | gpt-5.6-sol backoff 1.6s — upstream slow window" },
  { ts: offsetSeconds(404), level: "success", tag: "DONE",   message: "200 OK in 3.04s — 96 prompt + 148 completion tokens, $0.00196" },
  { ts: offsetSeconds(412), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-3" },
  { ts: offsetSeconds(413), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 21ms" },
  { ts: offsetSeconds(414), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 902 tok — 6.3k tok/s" },
  { ts: offsetSeconds(415), level: "success", tag: "DONE",   message: "200 OK in 2.81s — 198 prompt + 902 completion tokens, $0.00780" },
  { ts: offsetSeconds(424), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(425), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(426), level: "warn",    icon: "warning", tag: "HEADROOM", message: "headroom 6% — compression ratio 3.8× above soft limit" },
  { ts: offsetSeconds(426), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 204 tok — 4.8k tok/s" },
  { ts: offsetSeconds(427), level: "success", tag: "DONE",   message: "200 OK in 1.42s — 142 prompt + 204 completion tokens, $0.00274" },
  { ts: offsetSeconds(436), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-1" },
  { ts: offsetSeconds(437), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 23ms" },
  { ts: offsetSeconds(438), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 1,184 tok — 7.1k tok/s" },
  { ts: offsetSeconds(439), level: "success", tag: "DONE",   message: "200 OK in 3.91s — 224 prompt + 1,184 completion tokens, $0.01032" },
  { ts: offsetSeconds(448), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-5" },
  { ts: offsetSeconds(449), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 19ms" },
  { ts: offsetSeconds(450), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 312 tok — 4.9k tok/s" },
  { ts: offsetSeconds(451), level: "warn",    icon: "warning", tag: "TIER", message: "[TIER] CODEX | client disconnected before stream end" },
  { ts: offsetSeconds(452), level: "error",   icon: "cancel",  tag: "CANCELLED", message: "request aborted — client closed connection after 0.96s" },
  { ts: offsetSeconds(460), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-4" },
  { ts: offsetSeconds(461), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 25ms" },
  { ts: offsetSeconds(462), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 642 tok — 5.5k tok/s" },
  { ts: offsetSeconds(463), level: "success", tag: "DONE",   message: "200 OK in 1.93s — 184 prompt + 642 completion tokens, $0.00518" },
  { ts: offsetSeconds(472), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(473), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 16ms" },
  { ts: offsetSeconds(474), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 268 tok — 5.2k tok/s" },
  { ts: offsetSeconds(475), level: "success", tag: "DONE",   message: "200 OK in 1.27s — 104 prompt + 268 completion tokens, $0.00206" },
  { ts: offsetSeconds(484), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-3" },
  { ts: offsetSeconds(485), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 21ms" },
  { ts: offsetSeconds(486), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 824 tok — 6.4k tok/s" },
  { ts: offsetSeconds(487), level: "success", tag: "DONE",   message: "200 OK in 2.41s — 212 prompt + 824 completion tokens, $0.00712" },
  { ts: offsetSeconds(496), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-9" },
  { ts: offsetSeconds(497), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(498), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 412 tok — 4.4k tok/s" },
  { ts: offsetSeconds(499), level: "success", tag: "DONE",   message: "200 OK in 1.74s — 388 prompt + 412 completion tokens, $0.00412" },
  { ts: offsetSeconds(508), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-5" },
  { ts: offsetSeconds(509), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 19ms" },
  { ts: offsetSeconds(510), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 188 tok — 3.8k tok/s" },
  { ts: offsetSeconds(511), level: "success", tag: "DONE",   message: "200 OK in 1.08s — 72 prompt + 188 completion tokens, $0.00158" },
  { ts: offsetSeconds(520), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-1" },
  { ts: offsetSeconds(521), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 24ms" },
  { ts: offsetSeconds(522), level: "warn",    icon: "warning", tag: "HEADROOM", message: "headroom 4% — compression ratio 4.0× above soft limit" },
  { ts: offsetSeconds(522), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 942 tok — 6.7k tok/s" },
  { ts: offsetSeconds(523), level: "success", tag: "DONE",   message: "200 OK in 2.78s — 232 prompt + 942 completion tokens, $0.00822" },
  { ts: offsetSeconds(532), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(533), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(534), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 256 tok — 4.6k tok/s" },
  { ts: offsetSeconds(535), level: "success", tag: "DONE",   message: "200 OK in 1.34s — 96 prompt + 256 completion tokens, $0.00196" },
  { ts: offsetSeconds(544), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-4" },
  { ts: offsetSeconds(545), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 22ms" },
  { ts: offsetSeconds(546), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 712 tok — 5.9k tok/s" },
  { ts: offsetSeconds(547), level: "success", tag: "DONE",   message: "200 OK in 2.05s — 256 prompt + 712 completion tokens, $0.00564" },
  { ts: offsetSeconds(556), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-7" },
  { ts: offsetSeconds(557), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 17ms" },
  { ts: offsetSeconds(558), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 148 tok — 3.2k tok/s" },
  { ts: offsetSeconds(559), level: "warn",    icon: "warning", tag: "TIER", message: "[TIER] CODEX | gpt-5.6-sol backoff 2.0s — upstream slow window" },
  { ts: offsetSeconds(560), level: "success", tag: "DONE",   message: "200 OK in 3.42s — 96 prompt + 148 completion tokens, $0.00196" },
  { ts: offsetSeconds(568), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-3" },
  { ts: offsetSeconds(569), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 21ms" },
  { ts: offsetSeconds(570), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 902 tok — 6.3k tok/s" },
  { ts: offsetSeconds(571), level: "success", tag: "DONE",   message: "200 OK in 2.81s — 198 prompt + 902 completion tokens, $0.00780" },
  { ts: offsetSeconds(580), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=gpt-5.6-sol  key=key-2" },
  { ts: offsetSeconds(581), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol routed in 18ms" },
  { ts: offsetSeconds(582), level: "info",    tag: "TIER",   message: "[TIER] CODEX | gpt-5.6-sol streamed 204 tok — 4.8k tok/s" },
  { ts: offsetSeconds(583), level: "success", tag: "DONE",   message: "200 OK in 1.42s — 142 prompt + 204 completion tokens, $0.00274" },
  { ts: offsetSeconds(592), level: "info",    tag: "POST",   message: "/v1/chat/completions stream=200 model=cc/claude-fable-5  key=key-1" },
  { ts: offsetSeconds(593), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 routed in 23ms" },
  { ts: offsetSeconds(594), level: "info",    tag: "TIER",   message: "[TIER] CORTEX | cc/claude-fable-5 streamed 1,184 tok — 7.1k tok/s" },
  { ts: offsetSeconds(595), level: "success", tag: "DONE",   message: "200 OK in 3.91s — 224 prompt + 1,184 completion tokens, $0.01032" },
];

/** Fixed rolling-buffer summaries keep every Console view internally stable. */
export const LOG_BUFFER_TOTAL = 200;

export const LOG_LEVEL_COUNTS = [
  { value: "info", label: "Info", count: 171, tone: "info" },
  { value: "warn", label: "Warn", count: 26, tone: "warning" },
  { value: "error", label: "Error", count: 3, tone: "danger" },
];

export const LOG_STATS = [
  { label: "Entries", value: "200", icon: "subject" },
  { label: "Warnings", value: "12", icon: "warning", tone: "warning" },
  { label: "Errors", value: "3", icon: "error", tone: "danger" },
  { label: "Rate", value: "4.2/min", icon: "speed", tone: "accent" },
];

const VOLUME_COUNTS = [
  2, 3, 4, 3, 5, 4, 2, 3, 4, 5, 3, 4, 6, 5, 4, 3, 2, 4, 5, 4,
  3, 5, 6, 4, 3, 2, 4, 5, 7, 6, 4, 3, 5, 4, 2, 3, 4, 6, 5, 4,
  3, 5, 6, 7, 5, 4, 3, 2, 4, 5, 6, 4, 3, 5, 4, 6, 7, 5, 4, 3,
];

export const LOG_VOLUME = VOLUME_COUNTS.map((entries, index) => ({
  minute: index === 59 ? "Now" : `-${59 - index}m`,
  entries,
}));

export const LOG_TOP_SOURCES = [
  { source: "HEADROOM", count: 54 },
  { source: "RTK", count: 48 },
  { source: "TIER", count: 43 },
  { source: "POST/executors", count: 31 },
];
