import { forwardRef, useId } from "react";

import Field, { useFieldContext } from "./Field.jsx";

/**
 * Durin DS — Input.
 *
 * Text input with optional leading Material Symbols icon. `label`, `hint`, and
 * `error` create Field chrome. The error/hint ids are generated by Input and
 * shared with Field, so `aria-describedby` always points from the native
 * `<input>` to rendered help text. An outer manually-authored Field works too:
 * its context is read when this Input does not create its own Field.
 *
 * Remaining props (`type`, `value`, `placeholder`, `autoComplete`, …) spread
 * to the native input; its ref forwards there. Caller `aria-describedby` is
 * merged with Field's id (deduped — an externally-authored Field already
 * clones the same id onto this element, so context and props can overlap).
 * Both sizes retain a 44px minimum target.
 */
const Input = forwardRef(function Input(
  {
    label,
    hint,
    error,
    icon,
    size = "md",
    required = false,
    disabled = false,
    className,
    id,
    ...rest
  },
  ref,
) {
  const autoId = useId();
  const inputId = id ?? autoId;
  const messageId = `${inputId}-${error ? "error" : "hint"}`;
  const createsField = Boolean(label || hint || error);
  const outerField = useFieldContext();
  const fieldDescribedBy = createsField
    ? error || hint
      ? messageId
      : undefined
    : outerField?.describedBy;
  const callerDescribedBy = rest["aria-describedby"];
  const mergedDescribedBy =
    [...new Set([fieldDescribedBy, callerDescribedBy].filter(Boolean))].join(" ") || undefined;
  const ariaInvalid = Boolean(error) || outerField?.invalid || rest["aria-invalid"] || undefined;

  const inputClassName = [
    "w-full rounded-dd border border-dd-border bg-dd-surface text-dd-text outline-none transition-colors placeholder:text-dd-subtle",
    size === "sm" ? "min-h-11 px-2.5 text-xs" : "min-h-11 px-3 text-[13px]",
    icon ? (size === "sm" ? "pl-8" : "pl-9") : null,
    "hover:border-dd-border-subtle focus:border-dd-accent focus:shadow-dd-focus",
    "aria-invalid:border-dd-danger aria-invalid:hover:border-dd-danger aria-invalid:focus:border-dd-danger",
    "disabled:cursor-not-allowed disabled:opacity-60",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const control = (
    <div className="relative">
      {icon ? (
        <span
          aria-hidden="true"
          className={`pointer-events-none absolute inset-y-0 left-0 flex items-center ${
            size === "sm" ? "pl-2.5" : "pl-3"
          }`}
        >
          <span className="material-symbols-outlined text-[18px] leading-none text-dd-subtle">
            {icon}
          </span>
        </span>
      ) : null}
      <input
        ref={ref}
        id={inputId}
        type="text"
        required={required}
        disabled={disabled}
        className={inputClassName}
        {...rest}
        aria-invalid={ariaInvalid}
        aria-describedby={mergedDescribedBy}
      />
    </div>
  );

  if (createsField) {
    return (
      <Field
        label={label}
        hint={hint}
        error={error}
        required={required}
        htmlFor={inputId}
        hintId={hint ? messageId : undefined}
        errorId={error ? messageId : undefined}
      >
        {control}
      </Field>
    );
  }
  return control;
});

export default Input;
